name: Cancel stale queued runs

on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  actions: write
  contents: read

jobs:
  test-24h:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test action to cancel stale queued runs
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}

  test-12h:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test action to cancel stale queued runs
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          max_age_hours: 12
