name: Cancel stale queued runs

on:
  #  schedule:
  #    - cron: "0 * * * *"
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  actions: write
  contents: read

jobs:
  test-24h:
    runs-on: ubuntu-latest
    steps:
      - name: Test action to cancel stale queued runs
        uses: durandtibo/cancel-queued-runs-action@v0.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}

  test-12h:
    runs-on: ubuntu-latest
    steps:
      - name: Test action to cancel stale queued runs
        uses: durandtibo/cancel-queued-runs-action@v0.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          max_age_hours: 12
